### ISSUE TITLE
adding bst-user as plugin of brainstorm

### ISSUE THREAD

**Issue by Edouard2laire** [brainstorm-tools/bst-users#7]
Hi. 

Should we add this repo as a plugin of brainstorm to make the scripts here more visible and encourage more people to share scripts here? I guess we could regroup all the processes present here in a sub-group of processes called "users script". :)

**Comment by ftadel** [comment]
This is an interesting suggestion.
However, I'm not sure encouraging using this repository is something that we really want. 

If the user processes are supposedly useful for many users, they should be included directly in the main distribution (in `brainstorm3/process/functions/`, or as a plugin if there are many processes or extra data files needed).

Here, we are expecting to collect functions that are designed:
- to be useful only for the direct collaborators of the authors (too specific for being documented for the general audience) 
- to be used only by their author, when the author thinks that the code needs more work or that some parts of the code could be useful as the base for something more generic.

In both cases, these are not things we'd like the generic Brainstorm users to access easily. 
There is no curation/validation/maintenance requested for these functions, which makes them unsuitable for the standard distribution.

I'll keep the issue open though, as I might give it a second thought at some point in the future :)
Thank you for all your valuable suggestions and contributions to the project!

**Comment by rcassani** [comment]
This was added with #10 and https://github.com/brainstorm-tools/brainstorm3/pull/683
